### ISSUE TITLE
Wartungsmodus führt zu "Es ist ein Fehler aufgetreten"

### ISSUE THREAD

**Issue by michb** [contao/core-bundle#1307]
Aktiviert man im Contao 4.5.1 den Wartungsmodus wird anstatt der `service_unavailable.html.twig` die Standard-Fehlerseite "Es ist ein Fehler aufgetreten" angezeigt. Dies geschieht auch bei der Version 4.5.2.

Hebelt man den try-catch Block in
https://github.com/contao/core-bundle/blob/d1d428013260c02fbe86eacdc5764a3849e6e545/src/EventListener/PrettyErrorScreenListener.php#L271-L275

aus. So erhält man den folgenden Fehler:

```
[2018-01-12 12:36:04] app.CRITICAL: An exception occurred. {"exception":"[object] (Twig_Error_Runtime(code: 0): Block \"howToFix\" on template \"@ContaoCore/Error/layout.html.twig\" does not exist. at ../vendor/contao/core-bundle/src/Resources/views/Error/layout.html.twig:107)"} []
```

Schneller Fix ist ein eigenes `service_unavailable.html.twig` mit leerem `howToFix` und `explain` Block:

```
{% trans_default_domain 'contao_exception' %}
{% extends "@ContaoCore/Error/layout.html.twig" %}
{% block title %}
    {{ 'XPT.unavailable'|trans }}
{% endblock %}
{% block matter %}
    <p>{{ 'XPT.maintenance'|trans }}</p>
{% endblock %}
{% block howToFix %}
{% endblock %}
{% block explain %}
{% endblock %}
```

Man müsste evtl. den try-catch Block anpassen.
Recht unschön fand ich, dass der catch Block nichts ins Log schreibt und dass dieser Catch Block gar nicht verwendet wird, da eine `Twig_Error_Runtime Exception` geworfen wird. Liegt es an der verwendet Twig Version? Ein `composer show` liefert `twig/twig  v2.4.4`

**Comment by m-vo** [comment]
I can confirm this. 

Git history shows these blocks are missing ever since, so I assume Twig may have silently ignored that earlier on what could have been a bug?

**Comment by xchs** [comment]
In Contao 4.5.2 erhalte ich bei aktiviertem Wartungsmodus einen Error 503 im Frontend und folgenden Eintrag im Log:
```log
request.INFO: Matched route "contao_index". {"route":"contao_index","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","_route":"contao_index"},"request_uri":"https://example.com/","method":"HEAD"} []
security.INFO: Populated the TokenStorage with an anonymous Token. [] []
request.INFO: Matched route "contao_index". {"route":"contao_index","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","_route":"contao_index"},"request_uri":"https://example.com/","method":"GET"} []
security.INFO: Populated the TokenStorage with an anonymous Token. [] []
request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException: "" at /vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\ServiceUnavailableHttpException(code: 0):  at /vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Lexik\\Bundle\\MaintenanceBundle\\Exception\\ServiceUnavailableException(code: 0):  at /vendor/lexik/maintenance-bundle/Listener/MaintenanceListener.php:198)"} []
```

**Comment by m-vo** [comment]
I can confirm this. It does not happen with 4.5.0.

**Comment by m-vo** [comment]
Wait, this is weird. I've got a case where my custom `app/Resources/ContaoCoreBundle/views/Error/service_unavailable.html.twig` does not contain any blocks. Twig does not throw an error, but the response stays empty.

It turns out, that during the `kernel.response` event the content get set to `''` by the `ResponseListener` because the request method is `HEAD`. ([here](https://github.com/symfony/symfony/blob/aa5f7ea9b14478db8427b04976b23798e0580d87/src/Symfony/Component/HttpFoundation/Response.php#L291-L298))

**Comment by aschempp** [comment]
> It turns out, that during the kernel.response event the content get set to '' by the ResponseListener because the request method is HEAD.

f*ck, yet another header replay issue …

**Comment by Toflar** [comment]
How's that related to the replaying? It's a HEAD request, it's not allowed to have content.

**Comment by m-vo** [comment]
Is it possible that the `ServiceUnavailable` exception gets handled in the preflight request (which is a HEAD request) and then the actual response gets overwritten (now with empty content)? 

Maybe I can step through with the debugger tomorrow.

**Comment by Toflar** [comment]
The preflight response is only handled if it's `200 OK` and the `Content-Type` header matches, otherwise it's passed on directly which should be the case for a `500 Service Unavailable` response :)

**Comment by fritzmg** [comment]
I also notice that in the `prod` environment, any request that would normally cause a `500 Service Unavailable` response with the pretty error screen of Contao now simply results in an empty 500 response in Contao `4.5.2`.

**Comment by m-vo** [comment]
> The preflight response is only handled if it's 200 OK and the Content-Type header matches, otherwise it's passed on directly which should be the case for a 500 Service Unavailable response :)

I think this is what's happening:
- `fos_http_cache.pre_handle` -> `HeaderReplaySubscriber->preHandle()` executes preflight request:
  - `kernel.request` -> `MaintenanceListener` throws `ServiceUnavailableException` (503) 
  - `kernel.exception` -> `PrettyErrorScreenListener` kicks in, renders content
  - `kernel.response` -> `ResponseListener` removes content, because request is of type `HEAD`
- Preflight response (with empty content) gets set as event's response (because the status code does not match).
- Empty response gets delivered.

**Comment by m-vo** [comment]
I think the problem is that we cannot treat the response of the preflight request as if it was the real request in case it doesn't return with what the `HeaderReplayListener` has set on it. In this case it doesn't get executed because of the exception beeing thrown before. (It works if I return prematurely from `preHandle` or remove the `$duplicate->setMethod('HEAD');` from the code.)

So either we somehow change the type when an exception occurs (and gets handled) or we need to reexecute the request as we do not know it before sending the preflight one?

**Comment by Toflar** [comment]
> Why has this worked before?

Because the replay header bundle early aborted `kernel.response` events which was wrong and was fixed (otherwise security does not work). I could send a regular `GET` request instead of a  `HEAD` for the preflight request. That would solve this problem. @aschempp `?

**Comment by Toflar** [comment]
Generally speaking, there are two different maintenance modes. I'm calling them `Technical maintenance` and `Content maintenance`.

### Technical maintenance

* Application does not work (because of bugs or ongoing deployment)
* If you want to show a maintenance page here, you need to make sure it's not dependent from the application or even PHP. It also requires changes at your reverse proxy if you don't want it to continue serving pages from the cache.
* If you want to still be able to access the page, you need to be able to circumvent the reverse proxy somehow (or have a different domain).
* The maintenance page cannot be translated (or well, it has to be fully JS etc. because PHP is probably not available).
* You may use this to make changes at the code base.
* It's what Contao currently **does not** offer.

### Content maintenance

* Application is fully working. Maintenance is content-wise (lots of content changes, page structure etc.).
* The reverse proxy is able to determine (thanks to header replaying) if you're e.g. logged in to circumvent the cache because the application can respond.
* Template engine, translator etc. is all there so the maintenance page can be styled and translated as you wish.
* You **MUST NOT** use this maintenance mode to make changes on the code base.
* It's what Contao currently offers.

So we should consider our maintenance mode to be somehow a "weak" maintenance mode and it's the one we're talking about here and it's the one we need to fix.
@m-vo can you check if https://github.com/terminal42/header-replay-bundle/pull/7 fixes the problem?

**Comment by m-vo** [comment]
@Toflar The changes you made in https://github.com/terminal42/header-replay-bundle/pull/7 are working for me.

Ideally we should have a maintenance mode where users could install extensions (think of the Contao Manager). So this question might be connected with a best practice on how to write a Contao Bundle that won't crash in maintenance mode :-).

**Comment by Toflar** [comment]
> Ideally we should have a maintenance mode where users could install extensions (think of the Contao Manager). So this question might be connected with a best practice on how to write a Contao Bundle that won't crash in maintenance mode :-).

I don't think this will ever be possible. If you expect an installation to show a proper maintenance mode during setup changes it's easy what you have to do: Never touch any file on the production system but instead work with multiple setups and deployments.

BTW: terminal42/header-replay-bundle 1.4.1 is released. Update your dependencies, everyone.

**Comment by fritzmg** [comment]
> BTW: terminal42/header-replay-bundle 1.4.1 is released. Update your dependencies, everyone.

Unfortunately this does not fix the problem in Contao 4.5.2 where Contao simply responds with an empty response in the `prod` environment, whenever there was an error within a sub-request, e.g. when there is an error in a script included via `{{file::*}}`.

__Reproduction__:

* Create a file called `templates/foo.php`.
* Insert `<?php $this->foo();` into the file.
* Create a new HTML content element with the content `{{file::foo.php}}`.
* Open the front end in the `prod` environment.

You will only see a blank page from the `500` response.

**Comment by leofeyer** [comment]
I have fixed the initial problem in e2d88720f43fb9ca8bf6cd2e1a7f3b04d3fc0c89.

**Comment by fritzmg** [comment]
I have opened a new ticket for the other problem: #1321

**Comment by srhinow** [comment]
Bei mir unter Contao 4.6.7, PHP7.2 tritt das Problem auch auf.
Der letzte Eintrag aus der log-Datei ist folgender:

`[2018-11-08 21:13:32] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Error when rendering "http://www.zfib.de/_fragment?_hash=%2FqBeYf5LY3DkpKxI06SLYZn9I13vTAQeKy5ZMNA%2FvzQ%3D&_path=insertTag%3D%257B%257Bua%253A%253Aclass%257D%257D%26_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=17&request=netzwerk-junge-wissenschaft.html" (Status code is 503)." at /var/www/vhosts/hosting116127.a2f75.netcup.net/httpdocs/contao/vendor/symfony/http-kernel/HttpCache/AbstractSurrogate.php line 99 {"exception":"[object] (RuntimeException(code: 0): Error when rendering \"http://www.zfib.de/_fragment?_hash=%2FqBeYf5LY3DkpKxI06SLYZn9I13vTAQeKy5ZMNA%2FvzQ%3D&_path=insertTag%3D%257B%257Bua%253A%253Aclass%257D%257D%26_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=17&request=netzwerk-junge-wissenschaft.html\" (Status code is 503). at /var/www/vhosts/hosting116127.a2f75.netcup.net/httpdocs/contao/vendor/symfony/http-kernel/HttpCache/AbstractSurrogate.php:99)"} []`

Auch der Quelltext der 500-Fehlerseite sieht noch sehr komisch aus (er fängt in der Klasse an den Fehlercode-Template zu schreiben):
```
<body id="top" class="<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>An Error Occurred: Internal Server Error</title>
    </head>
    <body>
        <h1>Oops! An Error Occurred</h1>
        <h2>The server returned a "500 Internal Server Error".</h2>

        <div>
            Something is broken. Please let us know what you were doing when this error occurred.
            We will fix it as soon as possible. Sorry for any inconvenience caused.
        </div>
    </body>
```

**Comment by srhinow** [comment]
Ich habe gerade noch bemerkt das der 503er nur auftaucht, wenn ich mich im Backend angemeldet habe. Wenn ich nicht angemeldet bin kommt die Status-Seite "Dienst nicht verfügbar" was ja auch richtig ist. 
Wenn ich angemeldet bin und der Wartungsmodus aktiv ist, müsste ich doch aber die Website normal sehen können und kein 503er oder nicht?

**Comment by srhinow** [comment]
Da dieses Issue bereits geschlossen wurde habe ich ein neues hier geöffnet #176.
