### ISSUE TITLE
4.1.0-RC1 - impossible to access the installation tool

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#406]
After installing Contao, I can not access the installation tool.

Path: `http://localhost:8888/contao410rc/web/install.php`

Message: 
>The installation has not been completed. Open the Contao install tool to continue.
500 Internal Server Error - InternalServerErrorHttpException
1 linked Exception: IncompleteInstallationException

Logs:

>INFO - Matched route "contao_catch_all".
INFO - Attempting SimplePreAuthentication.
CRITICAL - An exception occurred.
CRITICAL - Uncaught PHP Exception Contao\CoreBundle\Exception\InternalServerErrorHttpException: "The installation has not been completed. Open the Contao install tool to continue." at /Applications/MAMP/htdocs/contao410rc/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 80 

And:

>RuntimeException in NativeSessionStorage.php line 144: Failed to start the session because headers have already been sent by "/Applications/MAMP/htdocs/contao410rc/app/bootstrap.php.cache" at line 1474.

**Comment by aschempp** [comment]
Did you install Contao using Composer? I assume it did create the `parameters.yml`?

**Comment by lionel-m** [comment]
>Did you install Contao using Composer?
Yes `php composer.phar create-project contao/standard-edition=4.1.0-RC1 contao410rc`

`parameters.yml` is ok

You're right, the folder `system/config` is empty

**Comment by leofeyer** [comment]
Fixed in contao/installation-bundle@4a519c0db9dd6f84a6e409246a9d533529d4b8e5. To test the fix, you have to **add** the following line to the "require" section of your `composer.json` file:

```json
    "require": {
        …
        "contao/installation-bundle": "dev-release/1.0.0",
    },
```

**Comment by lionel-m** [comment]
I added this line and after the composer update it returns:

![capture d ecran 2015-11-11 a 11 52 28](https://cloud.githubusercontent.com/assets/814476/11089547/e9ec8380-886a-11e5-99dd-d00abad0a6ce.png)

**Comment by leofeyer** [comment]
Yes, sorry, it should have been:

```json
    "require": {
        …
        "contao/core-bundle": "dev-release/4.1.0 as 4.1.x-dev",
    },
```

**Comment by lionel-m** [comment]
Thanks :+1:

**Comment by xchs** [comment]
Hmm, even with the `"contao/core-bundle": "dev-release/4.1.0 as 4.1.x-dev"` line in the `composer.json` require section and an dependency update by running `composer update` I still get an Error 500 when running the install tool (`/install.php`).

The `error_log` shows the following stack trace:
```
PHP Fatal error:  Uncaught exception 'Contao\\CoreBundle\\Exception\\IncompleteInstallationException' with message 'The installation has not been completed. Open the Contao install tool to continue.' in /var/www/virtual/contao4/vendor/contao/core-bundle/src/Framework/ContaoFramework.php:377

Stack trace:
#0 /var/www/virtual/contao4/vendor/contao/core-bundle/src/Framework/ContaoFramework.php(299): Contao\\CoreBundle\\Framework\\ContaoFramework->validateInstallation()
#1 /var/www/virtual/contao4/vendor/contao/core-bundle/src/Framework/ContaoFramework.php(147): Contao\\CoreBundle\\Framework\\ContaoFramework->initializeFramework()
#2 /var/www/virtual/contao4/vendor/contao/installation-bundle/src/HttpKernel/InstallationKernel.php(81): Contao\\CoreBundle\\Framework\\ContaoFramework->initialize()
#3 /var/www/virtual/contao4/vendor/contao/installation-bundle/src/HttpKernel/InstallationKernel.php(39): Contao\\InstallationBundle\\HttpKernel\\InstallationKernel->bo in /var/www/virtual/contao4/vendor/contao/core-bundle/src/Framework/ContaoFramework.php on line 377
```

**Comment by leofeyer** [comment]
I have just tried it with a fresh install and it worked like a charm.

```
composer create-project contao/standard-edition <target> dev-release/4.1.0
```

I have completed the Composer setup and then opened the install tool. It asked me to accept the license and to set a password and then completed the installation as usual.

**Comment by xchs** [comment]
Okay, thanks a lot. Setting up a new fresh install with
```
composer create-project contao/standard-edition . dev-release/4.1.0
```
did the trick. The installation went through without any problems now.

Yesterday, I did it as follows:

1. `composer create-project contao/standard-edition . 4.1.0-RC1`
2. Added the new requirement `"contao/core-bundle": "dev-release/4.1.0 as 4.1.x-dev"` to the `composer.json`
3. Executed the `composer update` command

Apparently, that was not the same. :confused:
