### ISSUE TITLE
[4.2.x] Filter positioning in page structure and Safari

### ISSUE THREAD

**Issue by stefansl** [contao/core-bundle#507]
After resizing the browser window from mobile to desktop size the filters in the page structure jump out of their wrapper. Only occurs in Safari (here: version 9.1.1).

Seems like a bug in Safari, because after de- and activating "position: absolute;" of ".styled_select" the positioning is correct again. 

![bildschirmfoto 2016-05-23 um 13 16 30](https://cloud.githubusercontent.com/assets/1564251/15469381/42a73368-20ea-11e6-8dea-2640cb599974.png)

**Comment by leofeyer** [comment]
I can confirm the issue, but I have no idea how to fix it. @contao/developers @JanoschOltmanns /cc

**Comment by JanoschOltmanns** [comment]
Same issue in 3.5.x. and no idea, how to fix it only with CSS ;)

But you can fix it with a wrapper:

```
/* stylect.js */
// Clone the template
if (!div) {
		div = Stylect.template.clone();
		new Element('div.stylect_wrapper').wraps(el);
		div.addClass(cls).inject(el, 'before');
}
```

```
/* stylect.css */
.stylect_wrapper {
	display: inline-block;
}
@media(max-width:767px) {
	.stylect_wrapper {
		display: block;
	}
}
```

**Comment by leofeyer** [comment]
Thanks a bunch @JanoschOltmanns. Fixed in fe722526f353bc264c21d77692e3c57dc9044926.

**Comment by leofeyer** [comment]
The change turns out to cause a lot of problems, therefore I'd like to revert it. However, we still need a fix for the initial issue. Can be a JavaScript fix, too.

**Comment by JanoschOltmanns** [comment]
Which problems?

**Comment by stefansl** [comment]
Does the problem still occur in Safari 10? If not, we should delete the fix, the issue appears quite rarely.

**Comment by leofeyer** [comment]
> Which problems?

I am currently trying to improve the responsiveness of the new back end theme by assigning a percentage width to all form fields by default. However, this only works if there is no wrapping element.

> Does the problem still occur in Safari 10? If not, we should delete the fix, the issue appears quite rarely.

I'll check.

**Comment by JanoschOltmanns** [comment]
What's about pure css?
![stylect--pure-css](https://cloud.githubusercontent.com/assets/8829909/18744417/36c5120c-80be-11e6-824a-2c1e02f36337.png)

**Comment by leofeyer** [comment]
Does that work in all browsers?

**Comment by JanoschOltmanns** [comment]
Not yet tested. Which browsers must be supported?

**Comment by leofeyer** [comment]
IE9+ I guess. I also found https://github.com/filamentgroup/select-css.

**Comment by JanoschOltmanns** [comment]
I will check it. My solution is based on http://foundation.zurb.com/sites/docs/forms.html#select-menus

**Comment by leofeyer** [comment]
I have used a foundation based solution now, thanks @JanoschOltmanns for pointing me there.
