### ISSUE TITLE
Problem mit MariaDB 10.2.4 oder höher

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core-bundle#918]
Ab MariaDB 10.2.4 ist das Wort "rows" nun reserviert
Siehe: https://mariadb.com/kb/en/mariadb/reserved-words/

Das führt bei der Installlation von Contao 4.4. zum Error:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows VARCHAR(8) DEFAULT '' NOT NULL`

```
[2017-07-03 13:26:17] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'CREATE TABLE tl_layout (id INT UNSIGNED AUTO_INCREMENT NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, tstamp INT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(255) DEFAULT '' NOT NULL, rows VARCHAR(8) DEFAULT '' NOT NULL, headerHeight VARCHAR(255) DEFAULT '' NOT NULL, footerHeight VARCHAR(255) DEFAULT '' NOT NULL, cols VARCHAR(8) DEFAULT '' NOT NULL, widthLeft VARCHAR(255) DEFAULT '' NOT NULL, widthRight VARCHAR(255) DEFAULT '' NOT NULL, sections BLOB DEFAULT NULL, framework VARCHAR(255) DEFAULT '' NOT NULL, stylesheet BLOB DEFAULT NULL, external BLOB DEFAULT NULL, orderExt BLOB DEFAULT NULL, loadingOrder VARCHAR(16) DEFAULT '' NOT NULL, combineScripts CHAR(1) DEFAULT '' NOT NULL, modules BLOB DEFAULT NULL, template VARCHAR(64) DEFAULT '' NOT NULL, doctype VARCHAR(32) DEFAULT '' NOT NULL, webfonts VARCHAR(255) DEFAULT '' NOT NULL, viewport VARCHAR(255) DEFAULT '' NOT NULL, titleTag VARCHAR(255) DEFAULT '' NOT NULL, cssClass VARCHAR(255) DEFAULT '' NOT NULL, onload VARCHAR(255) DEFAULT '' NOT NULL, head TEXT DEFAULT NULL, addJQuery CHAR(1) DEFAULT '' NOT NULL, jSource VARCHAR(16) DEFAULT '' NOT NULL, jquery TEXT DEFAULT NULL, addMooTools CHAR(1) DEFAULT '' NOT NULL, mooSource VARCHAR(16) DEFAULT '' NOT NULL, mootools TEXT DEFAULT NULL, picturefill CHAR(1) DEFAULT '' NOT NULL, analytics TEXT DEFAULT NULL, scripts TEXT DEFAULT NULL, script TEXT DEFAULT NULL, static CHAR(1) DEFAULT '' NOT NULL, width VARCHAR(255) DEFAULT '' NOT NULL, align VARCHAR(32) DEFAULT '' NOT NULL, calendarfeeds BLOB DEFAULT NULL, newsfeeds BLOB DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = MyISAM':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows VARCHAR(8) DEFAULT '' NOT NULL, headerHeight VARCHAR(255) DEFAULT '' NOT NU' at line 1 at /daten/contao4go/contao44maria.contaodev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows VARCHAR(8) DEFAULT '' NOT NULL, headerHeight VARCHAR(255) DEFAULT '' NOT NU' at line 1 at /daten/contao4go/contao44maria.contaodev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows VARCHAR(8) DEFAULT '' NOT NULL, headerHeight VARCHAR(255) DEFAULT '' NOT NU' at line 1 at /daten/contao4go/contao44maria.contaodev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
```

**Comment by leofeyer** [comment]
Das ist doch Sch**e. Sowas macht man doch nicht in einem Bugfix-Release! 😄

**Comment by leofeyer** [comment]
@contao/developers Wie lösen wir das? Mir wäre es am liebsten, wenn wir es erst in Contao 4.5 ändern würden. Dann wären beide LTS-Versionen aber nicht kompatibel zu MariaDB 10.2.4+.

**Comment by Mediaquery** [comment]
Hab mir den Code noch ned angeschaut aber "`rows`" sollte funktionieren...

**Comment by fritzmg** [comment]
Roundcube stumbled over this too: https://github.com/roundcube/roundcubemail/issues/5805

**Comment by fritzmg** [comment]
Technically `ROWS` is a reserved keyword in MySQL too. May be this is actually a case-sensitivity bug within MariaDB?

**Comment by fr0gM4ch1n3** [comment]
You can fix this error in
vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Updater.php on line 270

use:
$this->Database->query("ALTER TABLE `tl_layout` ADD ".$this->Database->escapeIdentifier('rows')." varchar(8) NOT NULL default ''");

instead of:
$this->Database->query("ALTER TABLE `tl_layout` ADD `rows` varchar(8) NOT NULL default ''");


tested with: mariadb: 10.2.6 & php 7.2

**Comment by leofeyer** [comment]
I doubt that this change will fix the issue. First of all, `$this->Database->escapeIdentifier('rows')` should return `` `rows` ``, so the two queries are the same. Second of all, the DBAL of the Contao 3 framework requires that field names do not use reserved keywords, because it does not escape them. So even if it works in the install tool, it will not in the rest of the system.

**Comment by leofeyer** [comment]
As discussed in Mumble on Thursday 13th, we want to try to escape the field as renaming would break all themes.

**Comment by leofeyer** [comment]
There seem to be more issues with MariaDB 10.2. I have just updated to MariaDB 10.2.7 and now the Doctrine schema tool is no longer working:

<img width="788" alt="" src="https://user-images.githubusercontent.com/1192057/28285204-22fc69a8-6b34-11e7-9310-225341f9720a.png">

@aschempp /cc

**Comment by leofeyer** [comment]
<img width="900" alt="" src="https://user-images.githubusercontent.com/1192057/28285771-2ccb995c-6b36-11e7-9787-bc2188916fd4.png">

It seems that there has been a change regarding the default value handling. The `$fromTable` dump has `"''"` and the `$toTable` dump has `""` for `_default`.

**Comment by leofeyer** [comment]
The following code in `Installer::dropNonContaoTables()` fixes the issue (for MariaDB only of course):

```php
        foreach ($schema->getTables() as $table) {
            foreach ($table->getColumns() as $column) {
                switch ($column->getDefault()) {
                    case "1":
                        $column->setDefault("'1'");
                        break;

                    case "''":
                        $column->setDefault('');
                        break;

                    case 'NULL':
                        $column->setDefault(null);
                        break;
                }
            }
        }
```

**Comment by leofeyer** [comment]
Also see: https://jira.mariadb.org/browse/MDEV-13132

**Comment by aschempp** [comment]
that sounds like a Doctrine issue actually? The default value should be an empty string or NULL, and not a string of quotes?

**Comment by leofeyer** [comment]
It is not a Doctrine issue.

https://github.com/MariaDB/server/commit/291411c96ceb914950731df6c36b32fc83b58acf

**Comment by leofeyer** [comment]
I can confirm that the issue only occurs in MariaDB 10.2.7, so I assume that it will be fixed in 10.2.8.

**Comment by leofeyer** [comment]
Ok, regarding the other issue: https://jira.mariadb.org/browse/MDEV-11878

**Comment by leofeyer** [comment]
In case the MariaDB developers decide not to revert the regression bug, we could fix the issue by adding the following to the `Installer` class in line 108:

```php
// Manually quote "rows", which has become a reserved keyword in MariaDB 10.2.4
// and is not handled in the MySQLKeywords class
if (false !== strpos($sql, ' rows ')) {
    $sql = str_replace(' rows ', ' `rows` ', $sql);
}
```

**Comment by leofeyer** [comment]
> Thank you for the bug report. Here is where we stand on this matter.
MariaDB 10.2 supports window functions, a feature which is not supported by MySQL 5.7 and lower. For this feature, ROWS is required to be marked as a reserved keyword. The SQL standard also tags ROWS as reserved.
>
>If you look at MySQL 8.0's implementation, their upcoming stable version, they have also marked ROWS as a reserved keyword. This is necessary, as they support window functions too. In this case, the problem should be resolved on the DBAL level and not within MariaDB/MySQL.
>
> Drupal considers ROWS as a reserved keyword for example.
https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words

**Comment by leofeyer** [comment]
So it will (have to) be fixed in Doctrine: https://github.com/doctrine/dbal/pull/2768

**Comment by aschempp** [comment]
Meanwhile we have to temporary escape this in Contao, right? I think in
 - `Model::save`
 - `DataContainer::save`
 - the install tool

**Comment by leofeyer** [comment]
Do we? Contao is simply not compatible with MariaDB 10.2 until the issue has been fixed in Doctrine. Version 10.1 is still active (even 10.0), so there is no urgent reason to update to MariaDB 10.2.

**Comment by aschempp** [comment]
Just because Doctrine escapes the column does not fix it in the Contao framework. We're not using the query builder or ORM, I hardly think Doctrine will parse the SQL and fix the escaping.

Also, you can't really control the dB version, so you're lucky if your Hoster does or does not update…

**Comment by BugBuster1701** [comment]
Na toll. Ist gefixt in dbal 2.6.0, leider nicht in der 2.5.13 (kam ein Tag vorher), denn die 2.6.0 hat neue Anforderungen bekommen:

- PHP 7.1.0 is the minimum supported PHP version
- The PDO extension is now a required dependency

Damit wird es dann wohl doch erst was in Contao 4.5? 
Oder doch noch eine Workaround Patch bis dahin?

**Comment by aschempp** [comment]
Ich denke nicht dass Contao hier etwas tun kann oder sollte. Wenn du MariaDB 10.2.4+ nutzt musst du halt auch PHP 7.1 nutzen. Composer wird dir das automatisch installieren falls der Server entsprechend ist.

**Comment by BugBuster1701** [comment]
Noch nicht, aber bald, aber dann ist auch PHP 7.1 dabei und sollte keine Probleme dann mehr machen.
Ursprünglich kam der Hinweis aus dem Forum, hab dort auch mal drauf hingewiesen.

**Comment by leofeyer** [comment]
Leider hilft auch das nicht, da das Contao 3 Framework das Keyword auch nicht gesondert behandelt. Ich habe PHP 7.1 und `doctrine/dbal` in der Version 2.6.1 und kann bei den Seitenlayouts trotzdem die Reihen nicht ändern:

```
An exception occurred while executing 'UPDATE tl_layout SET rows='2rwf' WHERE id='15'': SQLSTATE[42000]: Syntax error or access violation
```

Es wird wohl nicht anders gehen, als das Feld in der Datenbank umzubenennen. @ausi Können wir den Theme-Import und die Models etc. nicht so anpassen, dass das Feld gemappt wird?

**Comment by ausi** [comment]
Wäre das Problem im Contao-Framework nicht relativ schnell behoben indem man in [Contao/Database/Statement.php:196](https://github.com/contao/core-bundle/blob/2ec59c9ebb6579d4fb63ff992808ccfb64eb238b/src/Resources/contao/library/Contao/Database/Statement.php#L196) folgendes einbaut:

```
if (strtolower($k) === 'rows') {
	$k = '`rows`';
}
```

und die Spalte erst in Contao 4.5 umbenennt?

Andererseits ist Contao 4.4 eine LTS Version und somit würde der Fehler in den nächsten vier Jahren für alle auftreten die PHP < 7.1 mit MariaDB >= 10.2.4 einsetzen, sofern doctrine/dbal keinen bugfix in einer 2.5.x released.

Meine bevorzugte Variante wäre den bug im Contao-Framework zu fixen und `doctrine/dbal` zu bitten den bugfix auch in einer 2.5.x zu releasen. Wenn das nicht möglich ist müssen wir wohl die Spalte in der 4.4 umbenennen.

> Können wir den Theme-Import und die Models etc. nicht so anpassen, dass das Feld gemappt wird?

Theme-Import und Models könnten wir anpassen. Der SQL-Website-Import aus dem Install-Tool wird jedoch nicht kompatibel sein.

**Comment by leofeyer** [comment]
> Wäre das Problem im Contao-Framework nicht relativ schnell behoben

Ich glaube nicht, denn das Problem tritt ja nicht nur beim UPDATE auf, sondern auch beim SELECT. Und SELECT machen wir sowohl mittels `$db->prepare()` als auch mittels `LayoutModel::findBy`. Und der `DC_Table` macht beim Speichern vermutlich ein `UPDATE tl_layout SET rows=?` oder so.

**Comment by ausi** [comment]
Der DC_Table verwendet für das `UPDATE` auch die `set()` Methode und für den `SELECT`-Fall müsste wohl noch [Model/QueryBuilder.php:68](https://github.com/contao/core-bundle/blob/2ec59c9ebb6579d4fb63ff992808ccfb64eb238b/src/Resources/contao/library/Contao/Model/QueryBuilder.php#L68) angepasst werden:

```php
// Where condition
if ($arrOptions['column'] !== null)
{
	if (is_array($arrOptions['column'])) {
		$strColumn = implode(" AND ", $arrOptions['column']);
	}
	else {
		$strColumn = $arrOptions['column'];
		if (strtolower($strColumn) === 'rows') {
			$strColumn = '`rows`';
		}
		$strColumn = $arrOptions['table'] . '.' . $strColumn . "=?";
	}
	$strQuery .= " WHERE " . $strColumn;
}
```

**Comment by cryptedco** [comment]
Ich habe als Quickfix jetzt mal wie von @ausi vorgeschlagen

https://github.com/contao/core-bundle/blob/2ec59c9ebb6579d4fb63ff992808ccfb64eb238b/src/Resources/contao/library/Contao/Database/Statement.php#L196
und
https://github.com/contao/core-bundle/blob/2ec59c9ebb6579d4fb63ff992808ccfb64eb238b/src/Resources/contao/library/Contao/Model/QueryBuilder.php#L68

gepatched und dann nochmal im Statement.php obendrueber ("INSERT") creation auch einfach noch fies

$strQuery = str_replace("rows, ","`rows`, ",$strQuery);

reingebügelt... 

in Zeile 187: https://github.com/contao/core-bundle/blob/2ec59c9ebb6579d4fb63ff992808ccfb64eb238b/src/Resources/contao/library/Contao/Database/Statement.php#L187

jetzt geht es und kann natuerlich zu seltsamen effekten fuehren, wenn jemand einen Artikel schreibt, in dem "she brushed her eyebrows, and went" vorkommt :-), aber das sollte halten, bis es einen offziellen patch gibt...

**Comment by ausi** [comment]
> Meine bevorzugte Variante wäre den bug im Contao-Framework zu fixen und `doctrine/dbal` zu bitten den bugfix auch in einer 2.5.x zu releasen.

Das wird leider nicht passieren, siehe https://github.com/doctrine/dbal/pull/2768#issuecomment-324909227

Es bleibt uns also nichts anderes übrig als die Spalte umzubenennen. Die SQL-Struktur für den Website-Import ist dann von 4.4.3 nicht mit 4.4.4 kompatibel.

**Comment by cryptedco** [comment]
Es würde IMHO Sinn machen, die Spaltennamen in einem neuen Contao-Release zu escapen, vielleicht die beste Rangehensweise, da ich auch "cols" als Spaltenname gesehen habe...

**Comment by aschempp** [comment]
Ich sehe kein Problem darin das in Contao zu umgehen. Eine Änderung der Spalte halte ich für sehr problematisch. Da wir bei Queries immer `*` nutzen und updates immer mit `->set()` machen seh ich kein wirkliches Problem...

**Comment by ausi** [comment]
Ich denke das Issue kann geschlossen werden zugunsten von #1262

**Comment by mlwebworker** [comment]
Wie ist hier der aktuelle Stand?
Ich habe eine aktuelle Contao 4.4.20 mit Maria DB 10.2.10. Hoster Webgo
Auch hier funktioniert das Update der Tabellen nicht. Es kommt eine Latte an

`ALTER TABLE tl_article CHANGE stop stop VARCHAR(10) DEFAULT '' NOT NULL`

**Comment by fritzmg** [comment]
@mlwebworker welche PHP Version? Wie hast du Contao installiert?

**Comment by mlwebworker** [comment]
Installation über den Manager, letztes Update heute über die Konsole. 
PHP 7.2 in der Oberfläche des Webspaces und 
PHP 7.2.1 auf der Konsole 
Der Manager findet allerdings eine php7.2.7

**Comment by fritzmg** [comment]
Zeige mal den output von `composer show`

**Comment by mlwebworker** [comment]
Hier das Ergebnis
`
alnv/catalog-manager                      v1.22.10  Catalog Manager for Con...
clue/stream-filter                        v1.4.0    A simple and modern app...
composer/ca-bundle                        1.1.1     Lets you find a path to...
contao-community-alliance/composer-plugin 3.0.9     Composer plugin that pr...
contao-components/ace                     1.3.3     ACE code editor integra...
contao-components/chosen                  1.1.10    Chosen integration for ...
contao-components/colorbox                1.6.4.1   Colorbox integration fo...
contao-components/colorpicker             1.4.0.2   Color picker integratio...
contao-components/compass                 0.12.2.1  Compass integration for...
contao-components/contao                  7.1.5     Contao Open Source CMS ...
contao-components/datepicker              2.2.0.4   Date picker integration...
contao-components/dropzone                4.3.0     DropZone integration fo...
contao-components/highlight               8.9.1     Highlight.js integratio...
contao-components/html5shiv               3.7.3     HTML5 Shiv integration ...
contao-components/installer               1.3.0     Contao components insta...
contao-components/jquery                  1.12.4    jQuery integration for ...
contao-components/jquery-ui               1.12.1.1  jQuery UI integration f...
contao-components/mediabox                1.5.4.2   Mediabox integration fo...
contao-components/mediaelement            4.2.9     MediaElement.js integra...
contao-components/mootools                1.6.0.5   MooTools integration fo...
contao-components/respimage               1.4.2     Respimage.js integratio...
contao-components/simplemodal             2.0.8     SimpleModal integration...
contao-components/swipe                   2.0.6.2   A JavaScript touch slid...
contao-components/tablesort               3.4.10    Contao Open Source CMS ...
contao-components/tablesorter             2.0.5.6   jQuery tablesorter inte...
contao-components/tinymce4                4.6.7.2   TinyMCE 4 integration f...
contao/calendar-bundle                    4.4.20    Adds calendar functiona...
contao/comments-bundle                    4.4.20    Adds comments functiona...
contao/core-bundle                        4.4.20    Contao 4 core bundle
contao/faq-bundle                         4.4.20    Adds FAQ functionality ...
contao/image                              0.3.7     Contao image library
contao/imagine-svg                        0.2.1     Contao Imagine SVG library
contao/installation-bundle                4.4.20    Required to install and...
contao/listing-bundle                     4.4.20    Allows to list arbitrar...
contao/manager-bundle                     4.4.20    Contao 4 manager bundle
contao/manager-plugin                     2.5.0     Contao 4 manager plugin
contao/news-bundle                        4.4.20    Adds news functionality...
contao/newsletter-bundle                  4.4.20    Adds newsletter functio...
do-while/contao-backupdb-bundle           1.2.1     Backup of the Contao da...
doctrine/annotations                      v1.6.0    Docblock Annotations Pa...
doctrine/cache                            v1.7.1    Caching library offerin...
doctrine/collections                      v1.5.0    Collections Abstraction...
doctrine/common                           v2.9.0    Common Library for Doct...
doctrine/dbal                             v2.8.0    Database Abstraction Layer
doctrine/doctrine-bundle                  1.9.1     Symfony DoctrineBundle
doctrine/doctrine-cache-bundle            1.3.3     Symfony Bundle for Doct...
doctrine/event-manager                    v1.0.0    Doctrine Event Manager ...
doctrine/inflector                        v1.3.0    Common String Manipulat...
doctrine/lexer                            v1.0.1    Base library for a lexe...
doctrine/persistence                      v1.0.0    Doctrine Persistence ab...
doctrine/reflection                       v1.0.0    Doctrine Reflection com...
fig/link-util                             1.0.0     Common utility implemen...
friendsofsymfony/http-cache               2.4.0     Tools to manage HTTP ca...
friendsofsymfony/http-cache-bundle        2.4.0     Set path based HTTP cac...
guzzlehttp/guzzle                         6.3.3     Guzzle is a PHP HTTP cl...
guzzlehttp/promises                       v1.3.1    Guzzle promises library
guzzlehttp/psr7                           1.4.2     PSR-7 message implement...
imagine/imagine                           v0.7.1    Image processing for PH...
jdorn/sql-formatter                       v1.2.17   a PHP SQL highlighting ...
jeremykendall/php-domain-parser           3.0.0     Public Suffix List base...
jrgregory/m17-sticky-backend-footer       2.0.9     The sticky backend foot...
knplabs/knp-menu                          2.3.0     An object oriented menu...
knplabs/knp-menu-bundle                   v2.2.1    This bundle provides an...
knplabs/knp-time-bundle                   1.8.0     Knplabs time bundle mak...
leafo/scssphp                             v0.6.7    scssphp is a compiler f...
league/uri                                4.2.2     URI manipulation library
lexik/maintenance-bundle                  v2.1.5    This bundle allows you ...
madeyourday/contao-rocksolid-slider       v2.0.7    Responsive Slider. Full...
matthiasmullie/minify                     1.3.60    CSS & JavaScript minifi...
matthiasmullie/path-converter             1.1.1     Relative path converter
michelf/php-markdown                      1.8.0     PHP Markdown
monolog/monolog                           1.23.0    Sends your logs to file...
nelmio/cors-bundle                        1.5.4     Adds CORS (Cross-Origin...
nelmio/security-bundle                    2.5.1     Extra security-related ...
oyejorge/less.php                         v1.7.0.14 PHP port of the Javascr...
paragonie/random_compat                   v2.0.17   PHP 5.x polyfill for ra...
patchwork/utf8                            v1.3.1    Portable and performant...
php-http/client-common                    1.7.0     Common HTTP Client impl...
php-http/discovery                        1.4.0     Finds installed HTTPlug...
php-http/guzzle6-adapter                  v1.1.1    Guzzle 6 HTTP Adapter
php-http/httplug                          v1.1.0    HTTPlug, the HTTP clien...
php-http/message                          1.6.0     HTTP Message related tools
php-http/message-factory                  v1.0.2    Factory interfaces for ...
php-http/promise                          v1.0.0    Promise used for asynch...
phpspec/php-diff                          v1.1.0    A comprehensive library...
phpunit/php-token-stream                  1.4.12    Wrapper around PHP's to...
psr/cache                                 1.0.1     Common interface for ca...
psr/container                             1.0.0     Common Container Interf...
psr/http-message                          1.0.1     Common interface for HT...
psr/link                                  1.0.0     Common interfaces for H...
psr/log                                   1.0.2     Common interface for lo...
psr/simple-cache                          1.0.1     Common interfaces for s...
sensio/distribution-bundle                v5.0.22   Base bundle for Symfony...
sensio/framework-extra-bundle             v3.0.29   This bundle provides a ...
sensiolabs/ansi-to-html                   v1.1.3    A library to convert a ...
sensiolabs/security-checker               v4.1.8    A security checker for ...
simplepie/simplepie                       1.5.1     A simple Atom/RSS parsi...
swiftmailer/swiftmailer                   v5.4.12   Swiftmailer, free featu...
symfony/monolog-bundle                    v3.3.0    Symfony MonologBundle
symfony/polyfill-apcu                     v1.8.0    Symfony polyfill backpo...
symfony/polyfill-ctype                    v1.8.0    Symfony polyfill for ct...
symfony/polyfill-intl-icu                 v1.8.0    Symfony polyfill for in...
symfony/polyfill-mbstring                 v1.8.0    Symfony polyfill for th...
symfony/polyfill-php56                    v1.8.0    Symfony polyfill backpo...
symfony/polyfill-php70                    v1.8.0    Symfony polyfill backpo...
symfony/polyfill-util                     v1.8.0    Symfony utilities for p...
symfony/swiftmailer-bundle                v2.6.7    Symfony SwiftmailerBundle
symfony/symfony                           v3.4.13   The Symfony PHP framework
tecnickcom/tcpdf                          6.2.17    TCPDF is a PHP class fo...
terminal42/contao-conditionalformfields   2.2.1     conditionalformfields e...
terminal42/contao-easy_themes             2.2.8     Contao Open Source CMS ...
terminal42/header-replay-bundle           1.5.0     Send preflight requests...
true/punycode                             v2.1.1    A Bootstring encoding o...
twig/twig                                 v1.35.4   Twig, the flexible, fas...
ua-parser/uap-php                         v3.5.0    A multi-language port o...
webmozart/assert                          1.3.0     Assertions to validate ...
webmozart/path-util                       2.3.0     A robust cross-platform...
`
Habe mein Problem jetzt aber anders gelöst. Da die Datenbank aus einem Update einer 3er Version kam habe ich die DB exportiert. In eine lokale Installation 8mit allen benötigten Erweiterungen importiert, das DB Update durchlaufen lassen und dann die DB wieder auf den Server geschoben. Jetzt ist alles "sauber".

**Comment by asdfasdfasa** [comment]
Ich habe nach einer Installation einer Erweiterung ebenfalls eine Fehlermeldung bezüglich tl_layout und Maria DB.

Contao Version 4.4.28
PHP Version 7.1.25-1+0~20181207224650

[2019-01-07 11:14:01] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://www.xxx.ch/contao/install","method":"HEAD"} []
[2019-01-07 11:14:01] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://www.xxx.ch/contao/install","method":"GET"} []
[2019-01-07 11:14:01] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'xxxchwww' AND TABLE_NAME = 'tl_layout' ORDER BY ORDINAL_POSITION ASC AND COLUMN_NAME = 'sections'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:90, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88)"} []
[2019-01-07 11:16:24] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://www.xxx.ch/contao/install","method":"HEAD"} []
[2019-01-07 11:16:24] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://www.xxx.ch/contao/install","method":"GET"} []
[2019-01-07 11:16:24] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'xxxchwww' AND TABLE_NAME = 'tl_layout' ORDER BY ORDINAL_POSITION ASC AND COLUMN_NAME = 'sections'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:90, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88)"} []
[2019-01-07 11:24:52] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://www.xxx.ch/contao/install","method":"HEAD"} []
[2019-01-07 11:24:52] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://www.xxx.ch/contao/install","method":"GET"} []
[2019-01-07 11:24:52] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'xxxchwww' AND TABLE_NAME = 'tl_layout' ORDER BY ORDINAL_POSITION ASC AND COLUMN_NAME = 'sections'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:90, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND COLUMN_NAME = 'sections'' at line 1 at /webhome/xxx.ch/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88)"} []

**Comment by xchs** [comment]
Bei Fehlern solltest Du immer erst auf die aktuelle Version updaten (derzeit Contao 4.4.32)!

**Comment by asdfasdfasa** [comment]
Vielen Dank für deine Antwort, Hannes. Das stellt mich vor ein weiteres Problem. Wenn ich das richtig verstehe, ist es ohne SSH Zugang nicht (oder nicht ohne Probleme) möglich, ein Update zu machen.
Oder gibt es hier mittlerweile eine Lösung?

**Comment by fritzmg** [comment]
Wende dich an das Community Forum.
